version: "3.9"

services:
  lahelu-web:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3000-3002:3000"
    networks:
      - lahelu-network
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  lahelu-network:
    driver: bridge
